// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfPaFwyZhvCNg6mGXHVCV1nx2Y2vKsj3o',
    appId: '1:432927364391:web:04b925fb2a3f8cc635c502',
    messagingSenderId: '432927364391',
    projectId: 'chatapp-ab924',
    authDomain: 'chatapp-ab924.firebaseapp.com',
    storageBucket: 'chatapp-ab924.appspot.com',
    measurementId: 'G-H2XPF3GT1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQH16ezxcUCtCmcYOmO8LyEbfT2kFNqX4',
    appId: '1:432927364391:android:61a978f3b9e240ac35c502',
    messagingSenderId: '432927364391',
    projectId: 'chatapp-ab924',
    storageBucket: 'chatapp-ab924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE1xs63cp5WUAe9Ep2yRY1mqJR4aILThM',
    appId: '1:432927364391:ios:49cb9e5a5e4f2dae35c502',
    messagingSenderId: '432927364391',
    projectId: 'chatapp-ab924',
    storageBucket: 'chatapp-ab924.appspot.com',
    iosBundleId: 'com.example.practicals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE1xs63cp5WUAe9Ep2yRY1mqJR4aILThM',
    appId: '1:432927364391:ios:1485799492f47ab335c502',
    messagingSenderId: '432927364391',
    projectId: 'chatapp-ab924',
    storageBucket: 'chatapp-ab924.appspot.com',
    iosBundleId: 'com.example.practicals.RunnerTests',
  );
}
